### ISSUE TITLE
Craft 4 compatibility 🤔

### ISSUE THREAD

**Issue by jubalj** [levin-riegner/craft-cognito#8]
Hi There,

Thanks for your effort on supporting Cognito with craft. Does your code work with craft 4? 

Thanks
Jubal

**Comment by Alqueraf** [comment]
Hi, 

The plugin supports only Craft 3.

There are no plans to update it to Craft 4 at the moment, but the project is open to contributions.

**Comment by Alqueraf** [comment]
Craft 4 is now supported on the [0.8.0](https://github.com/levin-riegner/craft-cognito/releases/tag/v0.8.0) version
